### ISSUE TITLE
Converting to other formats

### ISSUE THREAD

**Issue by shahab-vahedi** [dolanskurd/AryanpourDictionary#2]
Hi Dolan,

Although I'm a proud owner of 2 Aryanpour dictionaries, it is the one that you provide that I use the most. Recently, I was in need of converting the MDict format to StarDict (*.ifo, *.idx, ...) using [pyglossary](https://github.com/ilius/pyglossary) [1], and I couldn't keep the formatting as nice as yours.

Is there any chance that you could also provide it in StarDict format and/or an open format like [XDXF](https://en.wikipedia.org/wiki/XDXF)?

[1]
```
pyglossary --utf8-check                            \
           --source-lang=English                   \
           --target-lang=Farsi                     \
           --read-options=same_dir_data_files=True \
           --write-options=sametypesequence=h      \
           "Aryanpour Dictionary.mdx"              \
           "aryanpour.ifo"
```

**Comment by 0xdolan** [comment]
> Hi Dolan,
> 
> 
> 
> Although I'm a proud owner of 2 Aryanpour dictionaries, it is the one that you provide that I use the most. Recently, I was in the need of converting the MDict format to StarDict (*.ifo, *.idx, ...) using [pyglossary](https://github.com/ilius/pyglossary) [1], and I couldn't keep the formatting as nice as yours.
> 
> 
> 
> Is there any chance that you could also provide it in StarDict format and/or an open format like [XDXF](https://en.wikipedia.org/wiki/XDXF)?
> 
> 
> 
> [1]
> 
> ```
> 
> pyglossary --utf8-check                            \
> 
>            --source-lang=English                   \
> 
>            --target-lang=Farsi                     \
> 
>            --read-options=same_dir_data_files=True \
> 
>            --write-options=sametypesequence=h      \
> 
>            "Aryanpour Dictionary.mdx"              \
> 
>            "aryanpour.ifo"
> 
> ```

Hey, I didn’t use Stardict. I’ll try to challenge myself in my free time, but I can’t promise. Why are you using that format? Using MDX/MDD is easier and more convenient.

**Comment by shahab-vahedi** [comment]
> Hey, I didn’t use Stardict. I’ll try to challenge myself in my free time, but I can’t promise. Why are you using that format? Using MDX/MDD is easier and more convenient.

For me, it's the [dictionary support](https://github.com/koreader/koreader/wiki/Dictionary-support) of [KOreader](https://github.com/koreader/koreader/), an open source ebook reader mostly targeting [eReaders](https://en.wikipedia.org/wiki/E-reader). StarDict as a program might be kind of abandoned, but its format is widely supported in many (open-source) dictionary programs like [Mobile GoldenDict](http://goldendict.mobi/) (paid), [QDict](https://f-droid.org/en/packages/com.annie.dictionary.fork/) , etc.

I totally get your point about "No Promise". You're doing this voluntarily in your free time.

**Comment by 0xdolan** [comment]
@shahab-vahedi I think I've found the issue. It may take some time to resolve, but I'll do my best to find the time and work on it

**Comment by 0xdolan** [comment]
I identified the issue: `.ifo` `.idx` `.dict` (Stardict format) doesn't accept external CSS files, so you must use inline styles directly within the HTML tags inside the dictionary file. This limitation is why no styles are appearing in the dictionary.

I created a simple example in Stardict format and tested it. In the screenshot, you can see that when you use inline styles within HTML tags, the styles are correctly applied.

![Screenshot-001](https://github.com/user-attachments/assets/dff0a1c4-bae1-4230-8a66-616e25b9ab70)

![Screenshot-002](https://github.com/user-attachments/assets/db5fbb42-0b77-4720-aee2-8916e95f5d23)

**Comment by 0xdolan** [comment]
Fix issue with styling in IFO (Stardict format) dictionaries

Resolved the problem where external CSS files were not accepted by `.ifo` `.idx` `.dict`, and inline styles were necessary. Added an example dictionary in Stardict format demonstrating the use of inline styles to ensure proper styling. This solution addresses the issue of missing styles in the dictionary files.

**Comment by shahab-vahedi** [comment]
> Added an example dictionary in Stardict format demonstrating the use of inline styles to ensure proper styling. This solution addresses the issue of missing styles in the dictionary files.

@0xdolan Where did you add this example? How can I retrieve it?

**Comment by 0xdolan** [comment]
> > Added an example dictionary in Stardict format demonstrating the use of inline styles to ensure proper styling. This solution addresses the issue of missing styles in the dictionary files.
> 
> @0xdolan Where did you add this example? How can I retrieve it?

Hey, I created it just for testing purposes.

**Comment by shahab-vahedi** [comment]
Could you then put a snippet of the HTML code here, so I can better understand what you were talking about? Preferably "before" and "after" your proposed changes. Thanks in advance.

**Comment by 0xdolan** [comment]
> Could you then put a snippet of the HTML code here, so I can better understand what you were talking about? Preferably "before" and "after" your proposed changes. Thanks in advance.

I deleted the example file. You can simply use HTML tags within the `.dict` file. For instance, if you have some entries in the `.dict` file, you can add a bold attribute to a word using the `<b>` tag, like this: `<b>entry</b>`, and that's it.
